services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy

  memory-worker:
    build:
      context: ./chat-service
      dockerfile: Dockerfile.worker
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy

  streamlit-ui:
    build:
      context: ./streamlit_ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      CHAT_API_URL: http://chat-service:8080
    depends_on:
      - chat-service
